# Generated by Django 4.1.7 on 2023-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='room',
            new_name='user',
        ),
    ]
